### ISSUE TITLE
missing abilities

### ISSUE THREAD

**Issue by Painted-Fox** [bil-bas/smash_and_grab#1]
I think the repository is missing some files.  When I try to run smash_and_grap.rbw I get the following error:

```
mrwerewolf@Argentarius ~/projects/smash_and_grab $ ruby bin/smash_and_grab.rbw 
/home/mrwerewolf/projects/smash_and_grab/lib/objects/entity.rb:3:in `require_relative': cannot load such file -- /home/mrwerewolf/projects/smash_and_grab/lib/abilities/ability (LoadError)
    from /home/mrwerewolf/projects/smash_and_grab/lib/objects/entity.rb:3:in `<top (required)>'
    from /home/mrwerewolf/projects/smash_and_grab/lib/main.rb:8:in `require_relative'
    from /home/mrwerewolf/projects/smash_and_grab/lib/main.rb:8:in `block in require_folder'
    from /home/mrwerewolf/projects/smash_and_grab/lib/main.rb:4:in `each'
    from /home/mrwerewolf/projects/smash_and_grab/lib/main.rb:4:in `require_folder'
    from /home/mrwerewolf/projects/smash_and_grab/lib/main.rb:62:in `<top (required)>'
    from bin/smash_and_grab.rbw:98:in `require_relative'
    from bin/smash_and_grab.rbw:98:in `<main>'
```

**Comment by bil-bas** [comment]
Oh, very sorry! The game is in early alpha and isn't really worth playing (and as you found out, doesn't work). I'm in the middle of a big refactor to make superpowers entirely generic, and I have several new files not under source control yet, although I kept adding/fixing unrelated stuff and I must have committed something incompletely. Anyway, shouldn't have pushed to the master branch where I am (or whatever lame excuse I can think of :D). No point just committing everything as it is, since the game is very broken right now :(

Sorry for wasting your time. Really the game isn't playable yet; you get nearly all the information about it just by looking at the two screenshots. My other 4 games should work properly though (http://spooner.github.com/games).

**Comment by Painted-Fox** [comment]
Hey no problem!  I'm not really planning on "playing" Smash and Grab in it's unfinished state.  I'm trying to get into game programming and I really like the work you did with Wrath.

I'm trying to make an old school turn-based strategy game with a few of my friends so I'm trying to pick apart your approach in Smash and Grab to help get me started.  I hope you don't mind.

**Comment by bil-bas** [comment]
Yeah, that is fine. I'd recommend you try the Gosu IRC channel (irc.freenode.net #gosu), which is a good place to discuss the finer points of making games with Gosu (and sometimes, my older code is not as good as it could be if I wrote it now from scratch and often has been pushed into new projects without being improved, so copying old code isn't always the most efficient way). And yes, feel free to peer at and copy all you want and ask if anything is a bit odd.

**Comment by Painted-Fox** [comment]
Thank you, I really appreciate it.

**Comment by bil-bas** [comment]
This has been fixed now. Sorry the repos was a bit messed up for a while!

**Comment by Painted-Fox** [comment]
Awesome. I look forward to seeing what you've got so far.
